# Generated by Django 4.1.3 on 2022-12-05 09:58

from django.db import migrations, models
import feeds.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=feeds.utils.news_image)),
                ('date_published', models.DateTimeField()),
                ('author', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
