# Generated by Django 4.1.3 on 2022-12-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
